#Enable remote dictionaries
org.lsst.ccs.remote.dictionary=true
#Point dictionaries and eprsistance to remote file server on lsstcam-tomcat
org.lsst.ccs.remote.server.uri.dictionaries=ccs://lsstcam-tomcat.cp.lsst.org/RestFileServer/
org.lsst.ccs.remote.server.uri.persistence=ccs://lsstcam-tomcat.cp.lsst.org/RestFileServer/

org.lsst.ccs.lockservice.enforceLevel=STRICT

#Accumulate and log message statistics
###org.lsst.ccs.messaging.accumulate.msg.statistics=true
###org.lsst.ccs.messaging.AgentMessagingLayer.level=FINE

org.jgroups.protocols.UDP.level=INFO
org.jgroups.protocols.PING.level=INFO
org.jgroups.protocols.MERGE3.level=INFO
org.jgroups.protocols.pbcast.GMS.level=INFO
org.jgroups.protocols.pbcast.NAKACK2.level=INFO
org.jgroups.JChannel.level=INFO

system.property.ccs.jg.physical=FINE
system.property.ccs.jg.connect=FINE
system.property.ccs.jg.retransmit=suppress:FINE;suppress-bundler:FINE;brief;WARNING
system.property.ccs.jg.hseqno=true
system.property.ccs.jg.member=coordinator:INFO
