system.property.ccs.jg.physical=FINE
system.property.ccs.jg.connect=FINE
system.property.ccs.jg.retransmit=brief;suppress:FINE;suppress-bundler:FINE;WARNING
org.jgroups.protocols.UDP.level=INFO
org.jgroups.protocols.PING.level=INFO
org.jgroups.protocols.MERGE3.level=INFO
org.jgroups.protocols.pbcast.GMS.level=FINE
org.jgroups.protocols.pbcast.NAKACK2.level=INFO
system.property.ccs.jg.hseqno=true
org.jgroups.JChannel.level=INFO
